### ISSUE TITLE
Error Warning 

### ISSUE THREAD

**Issue by Navegador** [misogi/vscode-ruby-rubocop#10]
Hi Misogi,

I am having an issue with the Ruby Rubocop extension for Visual Studio Code. At first I was getting an error saying that the ruby.rubocop.executePath was empty and now I am getting an error/warning  C: heodinprojectailsInstalleruby2.1.0inuby.exerubocop.bat is not executable. This is my execution path "C:\theodinproject\RailsInstaller\Ruby2.1.0\bin". I used the Rails Installer to install Ruby and Rails along with some other things all at the same time. Per the documentation I have found it says that it need to be the Ruby Binary Installation path. This shouldn't be that hard to set this extension up but for some reason I  have hit a snag.

Thank you,

Mario

**Comment by misogi** [comment]
Hi @Navegador .

I guess a rubocop execute was in Rails project directory. (not C:\theodinproject\RailsInstaller\Ruby2.1.0\bin)
Did you execute rubocop with like bundler? 
Is there rubocop in $(your project)/bin ?
A plugin can't work this situation.

Could you install rubocop without bundler and test how working?
    gem install rubocop

I should fix to work on standard rails project.

Thanks for your report.
