### ISSUE TITLE
SyntaxError while running Rubocop

### ISSUE THREAD

**Issue by orospakr** [misogi/vscode-ruby-rubocop#11]
![image](https://cloud.githubusercontent.com/assets/16714/13363132/ebc46d7e-dc95-11e5-9ac5-72db66cb116b.png)

If there is a better way to report the error, please let me know! Thank you.

**Comment by misogi** [comment]
Thanks for your report!
I guess this error is occured when rubocop command was not found.
I suppress this error on version 0.1.10.
