### ISSUE TITLE
Rubocop returns empty output

### ISSUE THREAD

**Issue by heldersantosmoreira** [misogi/vscode-ruby-rubocop#113]
I'm experiencing what to me seems like a very weird issue. 
Whenever the extension runs, I get this message on VS Code:

`command /Users/X/.rbenv/shims/rubocop returns empty output! please check configuration`

The error seems clear enough but... if I run the exact same command in the command line, I get a proper output. I've tried making some tweaks to the configurations, namely the execution path, using bundle or not, but nothing seems to solve it. 
I've dived in the code to see where this message was being given and this supposedly only happens if the output of the command is indeed empty, so I'm not sure what's going on.
Could I do something to see exactly what command is running to try and debug it?

Anyone experienced the same?

**Comment by loteresa2** [comment]
@heldersantosmoreira I'm facing the same issue. May I know what you did to resolve the issue?
thanks.

**Comment by heldersantosmoreira** [comment]
@loteresa2 I believe that in my case what was happening was that I was using a rubocop file that had some cops that were invalid (for the rubocop version I was using), and that was resulting in an empty output.

I remember downgrading to a version where the cop file was valid and went from there.

Sorry if this isn't too specific but let me know if if helps. If I remember something else, I'll be sure to let you know.

**Comment by ReneMoraales** [comment]
Just in case this helps anyone, I had a bad `.rubocop.yml` file in my home folder (`/Users/myusername/.rubocop.yml`) that was being loaded as part of the stack. Deleting it so it only used the project's configuration fixed it for me. Such a dumb fucking issue I've had for years, now finally fixed.

**Comment by calmerwaters** [comment]
@ReneMoraales  it was the lack of a `.rubocop.yml` in the actual project that did it for me here. As soon as I added one it, it was resolved in VS Code.

**Comment by SunnyWind** [comment]
My case is that I have a `.rubocop.yml` file in the project root, but the config content has dependencies not installed. After `bundle install`, Rubocop works well.

**Comment by Nassimadebeo** [comment]
i have the same problem

**Comment by philliplongman** [comment]
I'm not clear if this is the same issue @SunnyWind had. I had added a gem to the Gemfile, and was adding the configuration code, but I had not yet run Bundler. After I did, the error message stopped.

**Comment by Nassimadebeo** [comment]
I Replace `bin` in the PATH with `wrappers` and solved the issue:
**vscode setting:**
`ruby.rubocop.executePath": "/Users/USER_NAME/.rvm/gems/ruby-2.6.5/wrappers/`

**Comment by mirandashort** [comment]
I've been having this issue on and off and different things solve it. This time around, `gem uninstall rubocop` then `bundle install` fixed it

**Comment by 4Jcostelo** [comment]
> I Replace `bin` in the PATH with `wrappers` and solved the issue:
> **vscode setting:**
> `ruby.rubocop.executePath": "/Users/USER_NAME/.rvm/gems/ruby-2.6.5/wrappers/`

oh my god, whole day setting up rvm in this mac, and finally just got done with rubocop. Thank you

**Comment by dominiceden** [comment]
I use rbenv, and the issue was caused by me upgrading Rubocop from 0.68 to 1.17 - so a big jump. 

Many of my cops in my `.rubocop.yml` were deprecated or obsolete, so once I updated these cops it worked again in VSCode.

**Comment by alexanderadam** [comment]
@misogi if I understand this correctly, the `rubocop` command did not return anything in stdout because the command failed, right?
Would it possible to show the result in stderr instead in the error notification?

**Comment by brainmaniac** [comment]
> I Replace bin in the PATH with wrappers and solved the issue:
vscode setting:
ruby.rubocop.executePath": "/Users/USER_NAME/.rvm/gems/ruby-2.6.5/wrappers/

Thanks for this. I am running rbenv and for me in `.vscode/settings.json` I needed to add:
`"ruby.rubocop.executePath": "/Users/<username>/.rbenv/shims/"`
and reload window and then it worked

**Comment by oleingemann** [comment]
I solved this by making sure I could open vscode from the terminal. From Visual Studio Code, press Cmd+Shift + P and write "Shell command: Install 'code' command in PATH". Hit enter:

When activated, go to your project in the terminal and execute "code ."

I should then work as VSCode will pick up the environment you're using.

**Comment by quaos** [comment]
> I Replace `bin` in the PATH with `wrappers` and solved the issue: **vscode setting:** `ruby.rubocop.executePath": "/Users/USER_NAME/.rvm/gems/ruby-2.6.5/wrappers/`

I did this and still got "${HOME}/.rvm/gems/ruby-2.6.5/wrappers/rubocop returns empty output" interlaced with "...wrappers/rubocop is not executable"

**Comment by marvin-min** [comment]
@quaos Have you resolved this issue? I got the same issue again.

**Comment by quaos** [comment]
> @quaos Have you resolved this issue? I got the same issue again.

Not yet. I still have to run rubocop command set up as a project task.

**Comment by mikehulbert** [comment]
Encountered this error with asdf.

`which rubocop` to get the path.  Should return asdf with shims e.g. `/Users/_username_/.asdf/shims/rubocop`
replaced rubocop with `'bundle exec '` with trailing whitespace as below.

```json 
// settings.json
"ruby.rubocop.executePath": "/Users/_username_/.asdf/shims/bundle exec ",
"ruby.rubocop.useBundler": false,
```

**Comment by ramzieus** [comment]
If you are using a gem manager of installed ruby 
use the path provided by `where rubocop` and place it to rubocop settings 
of caurse after selecting the project gemset

**Comment by panacotar** [comment]
This happened to me and it might be associated to [vs-code-ruby being deprecated](https://github.com/rubyide/vscode-ruby). 
Check if your settings.json has `ruby.` and if it's greyed out.

![Screenshot 2023-11-03 at 11 42 54](https://github.com/misogi/vscode-ruby-rubocop/assets/62465430/88f26327-ce11-4fb6-822c-362db7ef45cf)

I installed `ruby-lsp` extension (search for **Shopify.ruby-lsp**) and added these settings:
```json
    "rubyLsp.formatter": "auto",
    "rubyLsp.rubyVersionManager": "rbenv",
    "[ruby]": {
        "editor.defaultFormatter": "Shopify.ruby-lsp",
        "editor.tabSize": 2,
        "editor.insertSpaces": true,
        "editor.semanticHighlighting.enabled": true,
    },
```
