### ISSUE TITLE
After installed vscode-ruby-rubocop, the langue type is not showed on the status bar.

### ISSUE THREAD

**Issue by magicwhite** [misogi/vscode-ruby-rubocop#13]
![Uploading rubocop.png…]()

**Comment by magicwhite** [comment]
![rubocop](https://cloud.githubusercontent.com/assets/8948783/13838322/034f15e4-ec4e-11e5-9709-c953862bb993.png)

**Comment by misogi** [comment]
Extension seems to conflict with [vscode-ruby](https://github.com/rebornix/vscode-ruby)

**Comment by magicwhite** [comment]
while it seem ok on latest insider version.

**Comment by typekpb** [comment]
no conflict for me as well, sounds like a candidate for closing

**Comment by misogi** [comment]
I check same issue on 0.11.x. I couldn't identify why this issue come from.
But ruby mode works fine on 1.x.x.
I only say vscode-ruby team is great. 😄
