### ISSUE TITLE
default settings.json error

### ISSUE THREAD

**Issue by yuhei-mukoyama** [misogi/vscode-ruby-rubocop#15]
先ほど VS Code をちゃんと利用し始めたばかりなので勘違いだったらすみません…。

read only になっているデフォルト設定ファイルにエラーが出てしまい、フッターに常に「エラー1」が表示されるような状況になってしまいました。

<img width="854" alt="2016-04-15 16 20 50" src="https://cloud.githubusercontent.com/assets/5656927/14554181/11bb6f30-0326-11e6-827b-f3d504396dc6.png">
<img width="265" alt="2016-04-15 16 19 49" src="https://cloud.githubusercontent.com/assets/5656927/14554182/11c0d916-0326-11e6-8e40-30eb6aa67b6e.png">

多分当プロジェクトのデフォルト設定情報が元だと思うのですが、もし違いましたら解決方法を教えていただけると幸いです。

宜しくお願い致します。

**Comment by misogi** [comment]
インストールとフィードバック下さりありがとう御座います。
設定項目 configFilePath がデフォルトの場合にエラーとなっているのを確認しました。

**Comment by misogi** [comment]
初期の設定値がエラーを起こしてしまうのを修正して、 v0.2.0 をリリースしました。
