### ISSUE TITLE
[Problem] Not support .rubocop.yml in current workspace

### ISSUE THREAD

**Issue by KSH-code** [misogi/vscode-ruby-rubocop#158]
When I do not have a config in root directory such as `~/.rubocop.yml` and I have a config `.rubocop.yml` in current workspace, warning messages are displayed.

so it needs to support using current workspace config without no settings.

particular rubocop versions cannot support absolute config path in current directory
- support: .rubocop.yml
- not support: /user/workspace/.rubocop.yml

I'm using rvm, ruby 2.7.1 and rubocop 1.3.1.

**Comment by KSH-code** [comment]
if no reply within 1week, I'm gonna fork and release a new extension to fix issues.

**Comment by mediafinger** [comment]
Hey @KSH-code I've seen that you forked it to: https://github.com/KSH-code/vscode-ruby-rubocop did you also release a fixed version?

As I am working on many projects with many different ruby and rubocop versions and many different .rubocop.yml files, the extension is in it's current state unfortunately not very helpful.

**Comment by KSH-code** [comment]
@mediafinger 
Not yet. I'll release fixed version in this week, because my work is too busy 😂

**Comment by KSH-code** [comment]
I've been discovering how it deploys. it may take a long time, because of the first time and it is a not my project.
