### ISSUE TITLE
Rubocop with RVM

### ISSUE THREAD

**Issue by SathyaBhat** [misogi/vscode-ruby-rubocop#23]
Hi,

I am trying to use have VS Code run rubocop when I save.

There are in my workspace settings json file:

    "ruby.rubocop.executePath": "/home/sathya/.rvm/bin/rvm-auto-ruby "

When I save however, I get this message:

    /home/sathya/.rvm/bin/rvm-auto-ruby rubocop is not executable

If I open the terminal type `rvm use 2.3` and then  `rubocop` in the terminal, rubocop works fine. What should I do to get vscode-ruby-rubocop running properly without errors on saving?

Thanks

**Comment by misogi** [comment]
HI,

This extension based on one executable.
Two command style like _rvm-auto-ruby rubocop_ is not compatible.

I think _rvm_ use 2.3_ provides a path to terminal only. not vscode.

I tested on rbenv instead of rvm.
It provides a path through desktop.

Same problems are may found rvm with TextMate, Sublime Text, and other editors.

**Comment by SathyaBhat** [comment]
Ah ok. Thanks for letting me know 👍

**Comment by betomoretti** [comment]
@SathyaBhat Which was the solution for make that rubocop works with vscode? I've got the same issue.

**Comment by SathyaBhat** [comment]
@betomoretti I didn't get it working, didn't look into it afterwards.

**Comment by misogi** [comment]
I tested with rvm.
these configs works fine.

`"ruby.rubocop.executePath": ""`
or 
delete "ruby.rubocop.executePath" config (use default == search $PATH)
or
`"ruby.rubocop.executePath": "/Users/you/.rvm/gems/ruby-2.3.2/bin/"`

**Comment by jamesotron** [comment]
Hey all.  I worked around this by creating a shell script called `rubocop`. I put it in `~/.vscode/bin` for convenience and changed the execute path to the same.

```bash
#!/bin/bash

export PATH="$PATH:~/.rvm/bin"
source ~/.rvm/scripts/rvm

cd `dirname $1`
exec bundle exec rubocop $@
```

**Comment by ctsstc** [comment]
@jimsynz I gave that a shot.

One thing to note is that you cannot seem to set the `Execute Path` to `~/.vscode/bin` you will need to use the full path it seems.

I get this error when I try that though

```
dirname: illegal option -- - usage: dirname path Could not locate Gemfile or .bundle/ directory
```

**Comment by cooljacob204** [comment]
Another note to anyone coming across this. @jimsynz post didn't fix it for me but it set me on the right track.

I did:

```
#!/bin/bash

source ~/.bash_profile > /dev/null
rvm ruby-version@my-gemset > /dev/null

exec bundle exec rubocop "$@"
```

/dev/null was necessary due to rubocop complaining about a non-json output.

**Comment by CornerstoneII** [comment]
@cooljacob204 
Do you mind explaining what this line does?

`rvm ruby-version@my-gemset > /dev/null`

**Comment by cooljacob204** [comment]
@CornerstoneII 

Sure, /dev/null is a device file that discards all data written to it.

What I am doing is suppressing the output of RVM by redirecting it's output (stdout) to /dev/null that way it's not included in the output from my bash script itself.

**Comment by TSMMark** [comment]
> Hey all. I worked around this by creating a shell script called `rubocop`. I put it in `~/.vscode/bin` for convenience and changed the execute path to the same.
> 
> ```shell
> #!/bin/bash
> 
> export PATH="$PATH:~/.rvm/bin"
> source ~/.rvm/scripts/rvm
> 
> cd `dirname $1`
> exec bundle exec rubocop $@
> ```

@jimsynz That saved me, thank you! Adapted the same idea into a script you can run to setup `~/.vscode/bin` from a shell script, or a copy & paste.

```shell
mkdir -p ~/.vscode/bin

cat <<'EOT' > ~/.vscode/bin/rubocop
#!/bin/bash

export PATH="$PATH:~/.rvm/bin"
source ~/.rvm/scripts/rvm

rvm use >/dev/null 2>&1
exec bundle exec rubocop $@
EOT

chmod +x ~/.vscode/bin/rubocop
```

Thanks again!
