### ISSUE TITLE
Lint on open

### ISSUE THREAD

**Issue by agross** [misogi/vscode-ruby-rubocop#29]
Hello,

first off, thanks for writing this extension!

I'd like to run rubocop when the file is opened in the editor without having to press a keyboard shortcut. Would you mind adding this feature?

Thanks!

**Comment by misogi** [comment]
Hello @agross.
This feature is sounds good to me.
First time I opened a ruby file. I had to edit and save.

Please let me know about event handler like onDidSaveTextDocument() if you know.

**Comment by agross** [comment]
https://code.visualstudio.com/Docs/extensionAPI/vscode-api

```ts
onDidOpenTextDocument: Event<TextDocument>
```

An event that is emitted when a text document is opened.

**Comment by agross** [comment]
Also see lint modes of Sublime Text.

http://www.sublimelinter.com/en/latest/lint_modes.html

This is my favorite and also the default:

> In background mode, lint requests are generated for every modification of a view, as well as on file loading and saving. This is the default mode.

**Comment by misogi** [comment]
I release a new version and executing rubocop also onDidOpenTextDocument.

**Comment by agross** [comment]
👍
