### ISSUE TITLE
"Error: No such file or directory:" on Git Differences

### ISSUE THREAD

**Issue by jnill-lutron** [misogi/vscode-ruby-rubocop#36]
With this extension enabled when selecting one of the files changed in VS Code's git window, this addon will raise an error "Error: No such file or directory: /4" every time a new difference is loaded (the number increments).  Presumably it is trying to run Rubocop on the difference file.

Ubuntu 16.04

VSCode:
Version 1.9.1
Commit f9d0c687ff2ea7aabd85fb9a43129117c0ecf519
Date 2017-02-08T23:44:55.542Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

Addons:
Ruby 0.10.4
ruby-rubocop 0.3.3

**Comment by stevensona** [comment]
Same issue on Windows 7. Error message is: "Error: No such file or directory: c:/20" The 20 can be replaced for other numbers.

VSCode 1.9.1
ruby-rubocop 0.3.3
ruby 2.3.3
rubocop 0.47.1

**Comment by misogi** [comment]
I confirmed same issue on macOS and fixed.
Please give us information about other isUntitled case if you discovered.

Thanks!
