### ISSUE TITLE
This plugin has no license, release it under MIT?

### ISSUE THREAD

**Issue by damien** [misogi/vscode-ruby-rubocop#39]
Hey @misogi!

While I was working on things I noticed that this repository is currently unlicensed. Unless you have strong feelings about maintaining full control over how this code is used, modified, or shared by others, I'd suggest picking an open source license like MIT (like [vscode-ruby](https://github.com/rubyide/vscode-ruby) does).

This is important because many people (like myself) can't safely use or share this code in a professional setting when licensing terms are unclear or unpermissive. For example, I'd be unable to include a copy of this extension with tools that automatically configure developer machines at my place of work.

If you are unfamiliar with how licensing works, Github has a good help document on the topic and the Chose a License website does a great job of walking people through the process of choosing a license:

* https://help.github.com/articles/licensing-a-repository/
* https://choosealicense.com/

Most of the time MIT is good enough for most people, though you may want GNU or Apache style license depending on how you desire this extension to be used/shared by others.

**Comment by misogi** [comment]
Thanks for very helpful information @damien !

I have been forgotten about license.
MIT license seems to be suitable for this project.
I will add documents about license. Please marge master if you need.

**Comment by misogi** [comment]
I choose MIT license.
