### ISSUE TITLE
Unrecognized cop error notification on save

### ISSUE THREAD

**Issue by angelocordon** [misogi/vscode-ruby-rubocop#45]
Hi there,

I'm new to VSCode and installed this extension. I'm seeing this error message on save now, and unsure why - I wasn't getting this error with a rubocop linter on Atom. I wonder if this is a bug within vscode-ruby-rubocop as it was [added](https://github.com/bbatsov/rubocop/blob/master/CHANGELOG.md#new-features-6) in Rubocop?

`Warning: unrecognized cop Performance/SortWithBlock`

**Comment by damien** [comment]
This isn't an issue with the VSCode extension--you'll get this error whenever you run an older version of Rubocop against configurations for newer versions of Rubocop. e.g. you have rubocop .37 and you have a .rubocop.yml intended for rubocop 0.42.

**Comment by angelocordon** [comment]
Oh I see, thanks for the clarification, Damien!

**Comment by damien** [comment]
@angelocordon No problem, thanks for reporting! While this wasn't an issue with the extension per-sey, I'm hoping a change I'm (sporadically) working on to this repo will help people avoid it by letting the extension be smarter about how it finds Rubocop on your system (see #34).
