### ISSUE TITLE
[ERROR] rubocop is not executable

### ISSUE THREAD

**Issue by andreleoni** [misogi/vscode-ruby-rubocop#57]
Stack: 
- Elementary OS 0.4.1 - Loki
- Visual Studio Code 1.17.2
- RVM 1.29.3
- Ruby 2.3.3
- Rubocop 0.48.1

I am trying to configure the rubocop, and I am getting the follow error: "WARN: /home/andre/.rvm/gems/ruby-2.3.3@artia/bin/rubocop + rubocop is not executable".

My actual Paths configuration...
Rubocop Config Path: "/home/andre/Documents/euax/artia-app/.rubocop.yml"
Rubocop Path: "/home/andre/.rvm/gems/ruby-2.3.3@artia/bin/rubocop"

My VSCode have the follow configuration:

> {
>     "workbench.colorTheme": "Quiet Light",
>     "editor.wordWrap": "on",
>     "editor.trimAutoWhitespace": true,
>     "files.trimTrailingWhitespace": true,
>     "window.zoomLevel": 0,
> 
>     "files.exclude": {
>         "log/*": true
>     },
> 
>     "typescript.check.npmIsInstalled": false,
> 
>     "ruby.rubocop.executePath": "/home/andre/.rvm/gems/ruby-2.3.3@artia/bin/rubocop",
>     "ruby.rubocop.configFilePath": "/home/andre/Documents/euax/artia-app/.rubocop.yml",
>     "ruby.rubocop.onSave": true
> }

I tried to change the executePath for only the "/home/andre/.rvm/gems/ruby-2.3.3@artia/bin/" without the rubocop complete path, and not works too...

What could be happening? Thanks!!!

**Comment by cyrilgandon** [comment]
Try to add a trailing `/`:

    "/home/andre/.rvm/gems/ruby-2.3.3@artia/bin/rubocop/"

**Comment by andreleoni** [comment]
I didn't understan what happened, but now, I removed the source of rubocop, and does worked...
If I have another problem, i write here, thanks for the help.

**Comment by faqndo97** [comment]
@andreleoni How do you remove the source of rubocop?

**Comment by rainer-uoy** [comment]
@andreleoni I would also like to know what you mean by removing the source of rubocop. Thanks!

**Comment by iampnelson** [comment]
@zachGl thank you, I too forgot to install the rubocop gem.  This solved the error.

**Comment by raywu** [comment]
@iampnelson @zachGl are you using RVM, and did you mean installing `rubocop` locally, or globally? I found this: https://pennyforyourcode.com/installing-a-ruby-gem-globally-in-rvm-ffa7222f7e7

**Comment by iampnelson** [comment]
@raywu I'm using rbenv and am setting it globally.

**Comment by zachGl** [comment]
@raywu 
I am using RVM. Remember to restart your code editor

**Comment by zachGl** [comment]
Just an extra reminder. I forgot to install the rubocop gem when I upgraded Ruby so I was getting the same error.
