### ISSUE TITLE
Spelling mistake in repository description

### ISSUE THREAD

**Issue by jbampton** [misogi/vscode-ruby-rubocop#73]
Hi @misogi  :) there is a spelling mistake at the top of the repository in the description -> rubocop extention for Visual Studio Code.  Should be 'extension'.

**Comment by misogi** [comment]
https://github.com/misogi/vscode-ruby-rubocop/pull/72 is merged. Thanks @jbampton .

**Comment by jbampton** [comment]
Hi @misogi this issue was not related to #72 .  

This is a small spelling mistake on GitHub in the description field.  In the image attached you have spelt 'extention' wrong, should be 'extension'  at the top above 170 commits.

![vscode](https://user-images.githubusercontent.com/418747/37249846-30be64ee-253b-11e8-88e9-f3fc0e35c249.png)

**Comment by misogi** [comment]
I thought it was in README. I have been fixed description in repository.
