### ISSUE TITLE
Cannot execute rubocop in WSL from Windows

### ISSUE THREAD

**Issue by rdrgn** [misogi/vscode-ruby-rubocop#76]
The file name of rubocop in WSL is `rubocop`, same as Linux. However, when VSCode is installed in Windows, `configuration.ts` tries to use `rubocop.bat`. So that, the extension cannot find the executable `rubocop` in WSL from VSCode in Windows.

> Error message
> my_path_to_rubocop_in_wsl/rubocop.bat is not executable

I need an additional configuration to use WSL. We can execute a file in WSL from Windows:

```
C:\> wsl my_path_to_rubocop_in_wsl/rubocop
```

**Comment by timkrins** [comment]
I use a workaround with a `.bat` file that I can reference in the vscode settings:

    @echo off
    bash.exe -c "~/.rvm/gems/ruby-2.5.0/wrappers/rubocop %*"

(I use rvm inside WSL, but you should be able to adjust for your own environment)

**Comment by rdrgn** [comment]
It works! My `rubocop.bat` looks like this. (I use `rbenv`.)

```bat
@echo off
wsl ~/.rbenv/shims/rubocop $^(echo '%*' ^| sed -e 's^|\\^|/^|g' -e 's^|\^([A-Za-z]\^)\:/\^(.*\^)^|/mnt/\L\1\E/\2^|g'^)
```

In the end, I needed to convert Windows path in args into WSL path.

https://gist.github.com/aseering/a06219e74c7f96ccea5ec65d5b2483b5

**Comment by pablox-cl** [comment]
@rdrgn can you tell me where did you put the `rubocop.bat` file?

**Comment by rdrgn** [comment]
@pablox-cl 
I created `C:\bin\rubocop.bat`. Then, I added the following to VSCode's `setting.json`.

```
"ruby.rubocop.executePath": "C:/bin/"
```

**Comment by luciuschoi** [comment]
I've tried along the above guide but an error message was shown up as follows:
```
-s/--stdin requires exactly one path, relative to the root of the project. RuboCop will use this path to determine which cops are enabled (via eg. Include/Exclude), and so that certain cops like Naming/FileName can be checked.
```
