### ISSUE TITLE
Specify rubocop configuration file

### ISSUE THREAD

**Issue by otg-kalex** [misogi/vscode-ruby-rubocop#9]
I couldn't find any information about how can I specify my config file. Is it possible?

**Comment by Navegador** [comment]
Hey otg-kalex it looks like the the config file will look something like this
{
    "ruby.rubocop.executePath": "D:/bin/Ruby22-x64/bin/",
    "ruby.rubocop.onSave": true
}

I am having some trouble wit the setup myself, as I had an issue with the exeutePath being empty an now I am getting an issue C: heodinprojectailsInstalleruby2.1.0nuby.exerubocop.bat is not executable. 
I'm planning on opening up an issue on this.

**Comment by otg-kalex** [comment]
@Navegador actually, I meant rubocop config like this `https://gist.github.com/jhass/a5ae80d87f18e53e7b56`. It works fine for me on mac.

**Comment by Navegador** [comment]
I see! That's my fault for misinterpreting. Do you think you could help me with my issue?

**Comment by otg-kalex** [comment]
@Navegador I think yes, when I have free time.

**Comment by Navegador** [comment]
@otg-kalex 
I think is a really issue to fix I think I am just getting confused or something is not matching. At first I was getting an error saying that the ruby.rubocop.executePath which was empty (I think this was my fault) and now I am getting an error/warning C: heodinprojectailsInstalleruby2.1.0inuby.exerubocop.bat is not executable. This is my execution path "C:\theodinproject\RailsInstaller\Ruby2.1.0\bin". I used the Rails Installer to install Ruby and Rails along with some other things like Git. I would assume my execution path is wrong.

**Comment by estebanz01** [comment]
any advance with this ?

**Comment by misogi** [comment]
@estebanz01 Thanks for your contribution :+1: 
PR merged and released 0.1.12.
